import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google"
import Topbar from "@/components/shared/Topbar";
import LeftSidebar from "@/components/shared/LeftSiderbar";
import RightSidebar from "@/components/shared/RightSiderbar";
import Bottombar from "@/components/shared/Bottombar";

const inter=Inter({subsets:["latin"]})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
}); 

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Threads",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ inter.className }
      >
        <ClerkProvider>
          <Topbar />

          <main className='main-container flex flex-row'>
            <LeftSidebar />
            <section className="flex-1 bg-gray-900">
              <div className='w-full'>
                  {children}
              </div>
            </section>
            <RightSidebar />
          </main>

          <Bottombar />
        </ClerkProvider>
      </body>
    </html>
  );
}